# Generated by Django 6.0 on 2025-12-20 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('diagnosting_description', models.TextField(max_length=500)),
                ('repairing_description', models.TextField(max_length=500)),
                ('testing_description', models.TextField(max_length=500)),
                ('status', models.CharField(choices=[('under_review', 'На рассмотрении'), ('diagnosing_issue', 'Выявление проблемы'), ('repairing', 'Ремонт'), ('testing', 'Тестирование'), ('ready_for_pickup', 'Готов к выдаче')], default='under_review', max_length=20)),
            ],
        ),
    ]
