# Generated by Django 6.0 on 2025-12-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechKeep', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='diagnosting_description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='repairing_description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('under_review', 'Поступил в обработку'), ('diagnosing_issue', 'Выявление проблемы'), ('repairing', 'Ремонт'), ('testing', 'Тестирование'), ('ready_for_pickup', 'Готов к использованию')], default='under_review', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='testing_description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
