# Generated by Django 6.0 on 2025-12-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechKeep', '0002_product_image_alter_product_diagnosting_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('mobile', 'Смартфоны'), ('tablet', 'Планшеты'), ('laptop', 'Ноутбуки'), ('pc', 'Компьютеры'), ('accessories', 'Аксессуары'), ('electronics', 'Электроника'), ('other', 'Другое')], default='other', max_length=20),
        ),
    ]
