# Generated by Django 6.0 on 2025-12-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechKeep', '0003_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('under_review', 'Поступил в обработку'), ('testing', 'Тестирование'), ('ready_for_pickup', 'Готов к использованию')], default='under_review', max_length=20),
        ),
    ]
