# Generated by Django 6.0 on 2026-01-05 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TechKeep', '0007_room_remove_product_user_product_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='diagnosting_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='testing_description',
        ),
    ]
