# Generated by Django 6.0 on 2026-01-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechKeep', '0008_remove_product_diagnosting_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(default='', max_length=32, unique=True),
            preserve_default=False,
        ),
    ]
