# Generated by Django 6.0 on 2026-01-06 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TechKeep', '0010_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
