# Generated by Django 6.0 on 2026-01-11 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TechKeep', '0013_product_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='user_id',
            new_name='user',
        ),
    ]
